config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :talks, only: [:show, :create, :destroy]
  resources :notifications, only: :index
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  has_many :notifications, dependent: :destroy
  
  validates :body, presence: true, length: { maximum:140 }
  validates :user_id, presence: true
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user_logged_in
  
  def create
    @post=Post.find(params[:post_id])
    @comment=@post.comments.new(comment_params)
    @comment.user_id=current_user.id
    if @comment.save
      flash[:success] = '送信しました。'
      #ここから通知レコード
      @post.create_notification_comment!(current_user, @comment.id)
      #ここまで
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = '送信できませんでした。'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @comment=Comment.find(params[:id])
    @comment.destroy
    flash[:success]='削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:body)
  end
  
end

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment], local: true) do |f| %>
  <%= f.text_field :body, placeholder: "コメントする..." %>
  <br>
  <%= hidden_field_tag :post_id, post.id %>
  <%= f.submit '送信', class: "btn btn-primary" %>
<% end %>

app/views/comments/_index.html.erb
<% comments.each do |comment| %>
  <hr>
  <div class="media-left">
    <% if @post.user.photo.present? %>
      <%= image_tag comment.user.photo.thumb50.url %>
    <% else %>
      <%= image_tag "icon.png", size: "50x50" %>
    <% end %>
    <%= link_to comment.user.name, user_path(comment.user) %><span class="text-muted">投稿日 <%= comment.created_at %></span>
    <% if current_user == comment.user %>
      <div class="dropdown float-right">
        <button class="btn dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
          <button class="dropdown-item" type="button">
            <%= link_to "削除", post_comment_path(post, comment), method: :delete, data: { confirm: "削除しますか?" } %>
          </button>
        </div>
      </div>
    <% end %>
  </div>
  <div class="media-body">
    <%= comment.body %>
  </div>
<% end %>