config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :talks, only: [:show, :create, :destroy]
  resources :notifications, only: :index
end

app/models/notification.rb
class Notification < ApplicationRecord
    default_scope -> { order(created_at: :desc) }
    belongs_to :post, optional: true
    belongs_to :comment, optional: true
    belongs_to :talk, optional: true
    
    belongs_to :visiter, class_name: 'User', foreign_key: 'visiter_id', optional: true
    belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
    @notifications = current_user.passive_notifications.page(params[:page]).per(10)
    #未確認の通知レコードを取り出した後、未確認→確認済みになるように
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unchecked_notifications
    @notifications=current_user.passive_notifications.where(checked: false)
  end
end

app/views/notifications/_notification.html.erb
<% notifications.each do |notification| %>
<% visiter=notification.visiter %>
<% visited=notification.visited %>


  <div class="media-left">
    <hr>
    <% if visiter.photo.present? %>
      <%= image_tag visiter.photo.thumb50.url %>
    <% else %>
      <%= image_tag "icon.png", size: "50x50" %>
    <% end %>
    <%= link_to visiter.name, user_path(visiter), style:"font-weight: bold;" %>
    <%= "が" %>
    <% case notification.action %>
      <% when "talk" then %>
        <%= "あなたに" %>
        <%= link_to 'DM', talk_path(visiter), style:"font-weight: bold;" %>
        <%= "しました" %>
      <div class="media-body">
        <%= Talk.find_by(id: notification.talk_id)&.content %>
        <div class="float-right">
          <%= time_ago_in_words(notification.created_at)+"前" %>
        </div>
      </div>
      <% when "comment" then %>
        <% if notification.post.user_id == visited.id %>
          <%= link_to 'あなたの投稿', notification.post, style:"font-weight: bold;" %>
        <% else %>
          <%= link_to notification.post.user.name+"さんの投稿", post_path(notification.post), style:"font-weight: bold;" %>
        <% end %>
        <%= "にコメントしました" %>
      <div class="media-body">
        <%= Comment.find_by(id: notification.comment_id)&.body %>
        <div class="float-right">
          <%= time_ago_in_words(notification.created_at)+"前" %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/notifications/index.html.erb
<% #自分のコメント、トークは表示しない %>
<% notifications=@notifications.where.not(visiter_id: current_user.id) %>
<div>
  <% if notifications.exists? %>
    <div class="user-index">
      <%= render "notifications/notification", notifications: @notifications %>
      <%= paginate notifications %>
    </div>
  <% else %>
    <p>通知はありません</p>
  <% end %>
</div>