config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users
  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
  resources :talks, only: [:show, :create, :destroy]
  resources :notifications, only: :index
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  
  validates :content, presence: true, length:{maximum: 255}
  validates :datetime, :place, length:{maximum: 30}
  
  def save_notification_comment!(current_user, comment_id, visited_id)
    #コメントは複数回することが考えられるため、一つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    #自分の投稿に対するコメントは、通知済みとする
    if notification.visiter_id == notification.visited_id
      notificaiton.checked = true
    end
    
    if notification.valid?
      notification.save
    end
  end
  
  def create_notification_comment!(current_user, comment_id)
    #自分以外のコメントしている人を全て取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    #まだ誰もコメントしていない場合は、投稿者に通知を送る
    if temp_ids.blank?
      save_notification_comment!(current_user, comment_id, user_id)
    end
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in, only: [:new, :show, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:destroy]
  
  def index
    if logged_in?
      @posts_apartment = Post.joins(:user).where("apartment=?", current_user.apartment).order(id: :desc).page(params[:page])
      @posts = Post.order(id: :desc).page(params[:page])
      @post = Post.new
    else
      @posts = Post.order(id: :desc).page(params[:page])
      @post = Post.new
    end
    
  end
  
  def new
    
  end
  
  def show
    @post=Post.find_by(id: params[:id])
    @comments=Comment.where(post_id: @post.id)
    @comment=Comment.new
  end
  
  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:success] = '投稿しました。'
      redirect_to root_url
    else
      @posts = current_user.posts.order(id: :desc).page(params[:page])
      flash.now[:danger] = '投稿できません。'
      render :new
    end
  end
  
  def edit
    @post = Post.find_by(id: params[:id])
    @user= User.find_by(id: params[:id])
  end

  def update
    @post= Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = '更新されました'
      redirect_to current_user
    else
      flash.now[:danger] = '更新されませんでした'
      render :edit
    end
  end

  def destroy
    @post=Post.find(params[:id])
    @post.destroy
    flash[:success] = '削除しました。'
    redirect_to posts_url
  end
  
  private

  def post_params
    params.require(:post).permit(:content, :datetime, :place)
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/views/posts/_new.html.erb
<div class="container">
  <%= form_with(model: post, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :とりあえず聞いてみる（必須）, class: 'control-label' %>
      <%= f.text_field :content, class: 'form-control', rows: 5 %>
      
      <div class="dropdown text-right">
        <button class="btn dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          +日時、場所を追加する
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
          <div class="dropdown-item">
            <%= f.label :日時（任意）, class: 'control-label' %>
            <%= f.datetime_local_field :datetime, class: "form-control" %>
          </div>
          <div class="dropdown-item">
            <%= f.label :場所（任意）, class: 'control-label' %>
            <%= f.text_field :place, class: 'form-control', rows: 5 %>
          </div>
        </div>
        <%= f.submit '投稿', class: 'btn btn-primary ' %>
      </div>
      
    </div>
    
  <% end %>
</div>

app/views/posts/_posts.apartment.html.erb
<div class="media-left">
  <div class="media-body">
    <% posts_apartment.each do |post| %>
      <hr>
      <% if post.user.photo.present? %>
        <%= image_tag post.user.photo.thumb50.url %>
      <% else %>
        <%= image_tag "icon.png", size: "50x50" %>
      <% end %>
      <% if current_user == post.user %>
        <div class="dropdown float-right">
          <button class="btn dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
            <button class="dropdown-item" type="button">
              <%= link_to '編集する', edit_post_path(post) %>
            </button>
            <button class="dropdown-item" type="button">
              <%= link_to "削除", post, method: :delete, data: { confirm: "削除しますか?" } %>
            </button>
          </div>
        </div>
      <% end %>
      <%= post.user.name %>
      <h5><%= link_to post.content, post_path(post) %></h5>
      <div>
        <% if post.datetime.present? %>
          日時：<%= post.datetime %>
        <% end %>
        </br>
        <% if post.place.present? %>
          場所：<%= post.place %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<%= paginate posts_apartment %>

app/views/posts/_posts.html.erb
<div class="media-left">
  <div class="media-body">
    <% posts.each do |post| %>
      <hr>
      <% if post.user.photo.present? %>
        <%= image_tag post.user.photo.thumb50.url %>
      <% else %>
        <%= image_tag "icon.png", size: "50x50" %>
      <% end %>
      <% if current_user == post.user %>
        <div class="dropdown float-right">
          <button class="btn dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
            <button class="dropdown-item" type="button">
              <%= link_to '編集する', edit_post_path(post) %>
            </button>
            <button class="dropdown-item" type="button">
              <%= link_to "削除", post, method: :delete, data: { confirm: "削除しますか?" } %>
            </button>
          </div>
        </div>
      <% end %>
      <%= link_to post.user.name, user_path(post.user) %>
      <h5><%= link_to post.content, post_path(post) %></h5>
      <div>
        <% if post.datetime.present? %>
          日時：<%= post.datetime %>
        <% end %>
        </br>
        <% if post.place.present? %>
          場所：<%= post.place %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<%= paginate posts %>

app/views/posts/edit.html.erb
<div class='container'>
  <h1 class='border-bottom'>投稿編集</h1>
  <%= form_with(model: @post, local: true) do |f| %>
    <div class="form-group">
      <%= f.label :用件, class: 'control-label' %>
      <%= f.text_area :content, class: 'form-control', rows: 5 %>
      
      <%= f.label :開始日時, class: 'control-label' %>
      <%= f.datetime_local_field :datetime, class: "form-control" %>
      
      <%= f.label :場所, class: 'control-label' %>
      <%= f.text_field :place, class: 'form-control', rows: 5 %>
    </div>
    <%= f.submit '更新', class: 'btn btn-primary btn-block' %>
  <% end %>
</div>

app/views/posts/index.html.erb
<% if logged_in? %>
  <% if current_user.apartment.present? %>
    <%= render 'posts/posts.apartment', posts_apartment: @posts_apartment %>
  <% else %>
    <%= render 'posts/new', post: @post %>
    <h6>
      ※現在、全国のユーザが表示されています
      </br>
      アパート・マンション名を
      <%= link_to "登録する", edit_user_path(current_user), class: "text-danger" %>
      と住人どうしで交流が出来ます
    <h6>
    <%= render 'posts/posts', posts: @posts %>
  <% end %>
<% else %>
  <%= render 'posts/new', post: @post %>
  <h6>
    ※現在、全国のユーザが表示されています
    </br>
    アパート・マンション名を
    <%= link_to "登録する", "#", class: "text-danger" %>
    と住人どうしで交流が出来ます
  <h6>
  <%= render 'posts/posts', posts: @posts %>
<% end %>

app/views/posts/show.html.erb
<div class="card mb-3" style="max-width: 500px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <% if @post.user.photo.present? %>
        <%= image_tag @post.user.photo.thumb100.url %>
      <% else %>
        <%= image_tag "icon.png", size: "100x100" %>
      <% end %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <%= link_to @post.user.name, user_path(@post.user) %>
        | 投稿日：<%= @post.created_at %>
      </div>
    </div>
    <%= @post.content %>
    </br>
    <% if @post.datetime.present? %>
      日時：<%= @post.datetime %>
    <% end %>
    </br>
    <% if @post.place.present? %>
      場所：<%= @post.place %>
    <% end %>
    <% if current_user == @post.user %>
      <div class="dropdown float-right">
        <button class="btn dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">
          <button class="dropdown-item" type="button">
            <%= link_to '編集する', edit_post_path(current_user) %>
          </button>
          <button class="dropdown-item" type="button">
            <%= link_to "削除", @post, method: :delete, data: { confirm: "削除しますか?" } %>
          </button>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div>
  <div class="card">
    <h3 class="text-center">コメント</h3>
    <%= render 'comments/index', comments: @comments, post: @post %>
    <%= render 'comments/form', post: @post, comment: @comment %>
  </div>
</div>